version: '3.8'

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx
    ports:
      - "443:443"

  wordpress:
    depends_on:
      - mariadb  
    build:
      context: ./wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html  

  mariadb:
    build:
      context: ./mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql #mariadb is a fork of mysql so theres compatibility

volumes:
  mariadb_data:  
  wordpress_data:  

networks: #allows the containers to "talk to eachother"
  ricky:
    driver: bridge
    # When you use the "bridge" network driver, 
    # containers attached to the same network can communicate with each other using their container names as hostnames.
