version: '3.8'

services:
  nginx:
    # depends_on:
    #   - wordpress
    container_name: nginx
    image: nginx_inception
    build:
      context: ./requirements/nginx
    # env_files: .env
    ports:
      - "443:443"
    networks:
      - ricky
    restart: always

  # wordpress:
#     depends_on:
#       - mariadb  
    # container_name: wordpress
    # build:
    #   context: ./wordpress
    # env_file: .env
#     volumes:
#       - wordpress_data:/var/www/html  

  # mariadb:
  #   container_name: mariadb
  #   build:
  #     context: ./mariadb
  #   env_file: .env
  #   volumes:
  #     - mariadb_data:/var/lib/mysql #mariadb is a fork of mysql so theres compatibility

# volumes:
#   mariadb_data:  
#   wordpress_data:  

networks: #allows the containers to "talk to eachother"
  ricky:
    driver: bridge
    # When you use the "bridge" network driver, 
    # containers attached to the same network can communicate with each other using their container names as hostnames.
